import type { Metadata } from "next";

import "./globals.css";
import Header from "./_components/_header/Header/Header";
import Footer from "./_components/_footer/Footer/Footer";

export const metadata: Metadata = {
  title: "Fictional cafe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
